name: CI-Ubuntu-20.04-LTS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ubuntu-2304-debian-build-test:
    strategy:
      matrix:
        image: ['ubuntu:23.04', 'debian:11', 'debian:12']
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    env:
      CC: gcc
      CXX: g++
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    steps:
      - name: Install packages
        run: |
          apt update
          apt install -y build-essential cmake gcc g++ python3 python3-dev python3-pip npm openjdk-17-jdk curl

      - uses: actions/checkout@v3

      - name: Ensure Python dependencies
        run: |
          pip install torch~=2.0.0 --extra-index-url https://download.pytorch.org/whl/cpu ${{ matrix.image != 'debian:11' && '--break-system-packages' }}
          pip install --user -r tools/python_api/requirements_dev.txt -f https://data.pyg.org/whl/torch-2.0.0+cpu.html ${{ matrix.image != 'debian:11' && '--break-system-packages' }}

      - name: Ensure Node.js dependencies
        run: npm install --include=dev
        working-directory: tools/nodejs_api

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-update-default-toolchain
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          $HOME/.cargo/bin/rustup toolchain install 1.67

      - name: Build and test
        run: make release NUM_THREADS=$(nproc)

      - name: C Example
        working-directory: examples/c
        run: |
          mkdir build -p
          cd build
          cmake ..
          cmake --build .

      - name: C++ Example
        working-directory: examples/cpp
        run: |
          mkdir build -p
          cd build
          cmake ..
          cmake --build .

      - name: Python test
        run: make pytest NUM_THREADS=$(nproc)
      
      - name: Node.js test
        run: make nodejstest NUM_THREADS=$(nproc)

      - name: Java test
        run: make javatest NUM_THREADS=$(nproc)

      - name: Rust share build
        # Share build cache when building rust API and the example project
        run: echo '[workspace]\nmembers = ["tools/rust_api","examples/rust"]' > Cargo.toml

      - name: Rust set env
        run: echo "CARGO_BUILD_JOBS=$(nproc)" >> $GITHUB_ENV

      - name: Rust test
        working-directory: tools/rust_api
        run: |
          cargo update -p half@2.3.1 --precise '2.2.1'
          cargo update -p time --precise '0.3.23'
          cargo test --features arrow -- --test-threads=1

      - name: Rust example
        working-directory: examples/rust
        run: cargo build --features arrow
