name: CI-Ubuntu-20.04-LTS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  windows-build-test:
    name: windows build & test
    strategy:
      matrix:
        runner: [windows-2019, windows-2022]
    runs-on: ${{ matrix.runner }}
    env:
      # Shorten build path as much as possible
      CARGO_TARGET_DIR: ${{ github.workspace }}/rs
    steps:
      - uses: actions/checkout@v3

      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Ensure Python dependencies
        shell: cmd
        run: |
          pip install torch~=1.13 --extra-index-url https://download.pytorch.org/whl/cpu
          pip install --user -r tools/python_api/requirements_dev.txt -f https://data.pyg.org/whl/torch-1.13.0+cpu.html

      - name: Ensure Node.js dependencies
        shell: cmd
        run: npm install --include=dev
        working-directory: tools/nodejs_api

      - name: Build and test
        shell: cmd
        run: make test NUM_THREADS=%NUMBER_OF_PROCESSORS%

      - name: C Example
        # temporarily disabled due to bug
        if: false
        shell: cmd
        working-directory: examples/c
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: C++ Example
        # temporarily disabled due to bug
        if: false
        shell: cmd
        working-directory: examples/cpp
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Python test
        # temporarily disabled due to bug
        if: false
        shell: cmd
        run: make pytest NUM_THREADS=%NUMBER_OF_PROCESSORS%

      - name: Node.js test
        shell: cmd
        run: make nodejstest NUM_THREADS=%NUMBER_OF_PROCESSORS%

      - name: Java test
        shell: cmd
        run: make javatest NUM_THREADS=%NUMBER_OF_PROCESSORS%

      - name: Rust test
        shell: cmd
        working-directory: tools/rust_api
        run: |
          set OPENSSL_DIR=C:\Program Files\OpenSSL-Win64
          set KUZU_TESTING=1
          set CFLAGS=/MDd
          set CXXFLAGS=/MDd /std:c++20
          set CARGO_BUILD_JOBS=%NUMBER_OF_PROCESSORS%
          cargo update -p half@2.3.1 --precise 2.2.1
          cargo update -p time --precise '0.3.23'
          cargo test -- --test-threads=1

      - name: Rust example
        shell: cmd
        working-directory: examples/rust
        run: |
          set CARGO_BUILD_JOBS=%NUMBER_OF_PROCESSORS%
          cargo build
