name: CI-Ubuntu-20.04-LTS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  simple-rust-test:
    name: simple rust test
    runs-on: ubuntu-20.04
    env:
      # Share build cache when building rust API and the example project
      CARGO_TARGET_DIR: ${{ github.workspace }}/target
      CARGO_BUILD_JOBS: $(nproc)
      CC: gcc
      CXX: g++
    steps:
      - uses: actions/checkout@v3

      - name: Rust test
        working-directory: tools/rust_api
        run: |
          cargo update -p half@2.3.1 --precise '2.2.1'
          cargo update -p time --precise '0.3.23'
          cargo test --features arrow -- --test-threads=1

      - name: Rust example
        working-directory: examples/rust
        run: cargo build
