name: CI-Ubuntu-20.04-LTS

on:
  workflow_dispatch:

jobs:
  ubuntu-2304-build-test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:23.04
    steps:
      - name: Install packages
        run: |
          apt update
          apt install -y build-essential cmake gcc g++ python3 python3-dev git

      - uses: actions/checkout@v3
        with:
          ref: 9fe713ebd1199f1fdc6614d818d1a7ad951a9edb

      - name: Build and test
        run: make test NUM_THREADS=$(nproc)
