name: CI-Ubuntu-20.04-LTS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  centos7-build-test:
    name: centos-7 build & test
    runs-on: ubuntu-latest
    # container:
    #   image: quay.io/pypa/manylinux2014_x86_64
    steps:
      # - uses: jlumbroso/free-disk-space@main
      #   with:
      #     tool-cache: true

      - run: cat /etc/os-release

      - uses: docker://quay.io/pypa/manylinux2014_x86_64
        continue-on-error: true
        with:
          args: mkdir asdf

      - uses: docker://quay.io/pypa/manylinux2014_x86_64
        continue-on-error: true
        with:
          args: ls -al
