name: CI-Ubuntu-20.04-LTS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ubuntu-2304-debian-build-test:
    strategy:
      matrix:
        image: ['debian:11']
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    env:
      CC: gcc
      CXX: g++
    steps:
      - name: Install packages
        run: |
          apt update
          apt install -y build-essential cmake gcc g++ python3 python3-dev python3-pip npm openjdk-17-jdk curl

      - uses: actions/checkout@v3

      - run: cmake --version

      - name: Build and test
        run: make release NUM_THREADS=$(nproc)
