name: CI-Ubuntu-20.04-LTS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  arch-build-test:
    runs-on: ubuntu-latest
    container:
      image: arch:latest
    env:
    steps:
      - name: Install Arch Linux packages
        run: |
          whoami
          pacman -Syu
          pacman -S --needed base-devel cmake gcc python nodejs jdk17-openjdk rust

      - uses: actions/checkout@v3

      - name: Ensure Python dependencies
        run: |
          pip install torch~=1.13 --extra-index-url https://download.pytorch.org/whl/cpu
          pip install --user -r tools/python_api/requirements_dev.txt -f https://data.pyg.org/whl/torch-1.13.0+cpu.html

      - name: Ensure Node.js dependencies
        run: npm install --include=dev
        working-directory: tools/nodejs_api

      - name: Build and test
        run: make test NUM_THREADS=$nproc
