name: CI-Ubuntu-20.04-LTS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  arch-build-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/archlinux/archlinux:latest
    steps:
      - name: Install Arch Linux packages
        run: |
          pacman -Syu
          yes | pacman -S --needed base-devel git cmake gcc python python-pip  nodejs jdk17-openjdk rust 

      - uses: actions/checkout@v3

      - name: Ensure Python dependencies
        run: |
          pip install torch~=2.0.0 --extra-index-url https://download.pytorch.org/whl/cpu --break-system-packages
          pip install -r tools/python_api/requirements_dev.txt -f https://data.pyg.org/whl/torch-2.0.0+cpu.html --break-system-packages

      - name: Ensure Node.js dependencies
        run: npm install --include=dev
        working-directory: tools/nodejs_api

      - name: Build and test
        run: make test NUM_THREADS=$nproc

      - name: Python test
        run: make pytest NUM_THREADS=$nproc
      
      - name: Node.js test
        run: make nodejstest NUM_THREADS=$nproc

      - name: Java test
        run: make javatest NUM_THREADS=$nproc
      
      - name: C Example
        working-directory: examples/c
        run: |
          mkdir build -p
          cd build
          cmake ..
          cmake --build .

      - name: C++ Example
        working-directory: examples/cpp
        run: |
          mkdir build -p
          cd build
          cmake ..
          cmake --build .
  
