name: CI-Ubuntu-20.04-LTS

on:
  workflow_dispatch:
    inputs:
      refToBuild:
        description: 'Branch, tag or commit SHA1 to build'
        required: false
        type: string

jobs:
  ubuntu-2304-build-test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:23.04
    steps:
      - name: Install packages
        run: |
          apt update
          apt install -y build-essential cmake gcc g++ python3 python3-dev

      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.refToBuild }}

      - name: Build and test
        run: make test NUM_THREADS=$(nproc)
