name: CI-Ubuntu-20.04-LTS

on:
  workflow_dispatch:

jobs:
  ubuntu-2004-build-test:
    name: ubuntu-20.04 build & test
    runs-on: ubuntu-20.04
    env:
      CC: gcc
      CXX: g++
    steps:
      - uses: actions/checkout@v3

      - name: Build and test
        run: make test NUM_THREADS=$(nproc)
