name: CI-Ubuntu-20.04-LTS

on:
  workflow_dispatch:

jobs:
  windows-build-test:
    name: windows build & test
    strategy:
      matrix:
        runner: [windows-2019]
    runs-on: ${{ matrix.runner }}
    steps:
      - run: choco install openssl
      - name: test
        shell: cmd
        run: |
          dir "C:\Program Files"
          dir "C:\Program Files (x86)"
