name: CI-Ubuntu-20.04-LTS

on:
  workflow_dispatch:

jobs:
  windows-build-test:
    name: windows build & test
    strategy:
      matrix:
        runner: [windows-2019, windows-2022]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: test
        shell: cmd
        run: |
          dir C:\Program Files
          dir C:\Program Files (x86)
          dir C:\Program Files\OpenSSL-Win64
          dir C:\Program Files (x86)\OpenSSL-Win64
