name: CI-Ubuntu-20.04-LTS

on:
  workflow_dispatch:

jobs:
  windows-build-test:
    name: windows build & test
    strategy:
      matrix:
        runner: [windows-2019]
    runs-on: ${{ matrix.runner }}
    steps:
      # - run: vcpkg install openssl:x64-windows-static-md
      - name: test
        shell: cmd
        run: |
          dir "C:\"
