name: CI-Ubuntu-20.04-LTS

on:
  workflow_dispatch:
    inputs:
      refToBuild:
        description: 'Branch, tag or commit SHA1 to build'
        required: false
        type: string

jobs:
  ubuntu-2004-build-test:
    name: ubuntu-20.04 build & test
    runs-on: ubuntu-20.04
    env:
      CC: gcc
      CXX: g++
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.refToBuild }}

      - name: Build and test
        run: make release NUM_THREADS=$(nproc)
      
      - name: Rust share build
        # Share build cache when building rust API and the example project
        run: echo $'[workspace]\nmembers = ["tools/rust_api","examples/rust"]' > Cargo.toml

      - name: Rust set env
        run: echo "CARGO_BUILD_JOBS=$(nproc)" >> $GITHUB_ENV

      - name: Rust test
        working-directory: tools/rust_api
        run: |
          cargo update -p half@2.3.1 --precise '2.2.1'
          cargo update -p time --precise '0.3.23'
          cargo test --features arrow -- --test-threads=1

      - name: Rust example
        working-directory: examples/rust
        run: cargo build
